let money = prompt('Сколько у тебя денег?')
let apple = prompt('Сколько яблок ты купил?')
let bread = prompt('Сколько батонов хлеба ты купил?')
let applesPrice = prompt('Сколько стоит одно яблоко?')
let apples = Number(applesPrice)*Number(apple)
let breadsPrice = prompt('Сколько стоит один батон?')
let breads = Number(breadsPrice)*Number(bread)
let goods = Number(breads)+Number(apples)
document.body.innerHTML = Number(goods) <= Number(money)